In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
print(tf.__version__)

2.2.0


In [2]:
dataset = tf.data.Dataset.range(10)
dataset

<RangeDataset shapes: (), types: tf.int64>

In [9]:
help(dataset.batch)

Help on method batch in module tensorflow.python.data.ops.dataset_ops:

batch(batch_size, drop_remainder=False) method of tensorflow.python.data.ops.dataset_ops.WindowDataset instance
    Combines consecutive elements of this dataset into batches.
    
    >>> dataset = tf.data.Dataset.range(8)
    >>> dataset = dataset.batch(3)
    >>> list(dataset.as_numpy_iterator())
    [array([0, 1, 2]), array([3, 4, 5]), array([6, 7])]
    
    >>> dataset = tf.data.Dataset.range(8)
    >>> dataset = dataset.batch(3, drop_remainder=True)
    >>> list(dataset.as_numpy_iterator())
    [array([0, 1, 2]), array([3, 4, 5])]
    
    The components of the resulting element will have an additional outer
    dimension, which will be `batch_size` (or `N % batch_size` for the last
    element if `batch_size` does not divide the number of input elements `N`
    evenly and `drop_remainder` is `False`). If your program depends on the
    batches having the same outer dimension, you should set the `drop_remain

In [8]:
help(dataset.window)

Help on method window in module tensorflow.python.data.ops.dataset_ops:

window(size, shift=None, stride=1, drop_remainder=False) method of tensorflow.python.data.ops.dataset_ops.WindowDataset instance
    Combines (nests of) input elements into a dataset of (nests of) windows.
    
    A "window" is a finite dataset of flat elements of size `size` (or possibly
    fewer if there are not enough input elements to fill the window and
    `drop_remainder` evaluates to `False`).
    
    The `shift` argument determines the number of input elements by which the
    window moves on each iteration.  If windows and elements are both numbered
    starting at 0, the first element in window `k` will be element `k * shift`
    of the input dataset. In particular, the first element of the first window
    will always be the first element of the input dataset.
    
    The `stride` argument determines the stride of the input elements, and the
    `shift` argument determines the shift of the window.


In [3]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1)
dataset

<WindowDataset shapes: DatasetSpec(TensorSpec(shape=(), dtype=tf.int64, name=None), TensorShape([])), types: DatasetSpec(TensorSpec(shape=(), dtype=tf.int64, name=None), TensorShape([]))>

In [4]:
for window in dataset:
    print(window)

<_VariantDataset shapes: (), types: tf.int64>
<_VariantDataset shapes: (), types: tf.int64>
<_VariantDataset shapes: (), types: tf.int64>
<_VariantDataset shapes: (), types: tf.int64>
<_VariantDataset shapes: (), types: tf.int64>
<_VariantDataset shapes: (), types: tf.int64>
<_VariantDataset shapes: (), types: tf.int64>
<_VariantDataset shapes: (), types: tf.int64>
<_VariantDataset shapes: (), types: tf.int64>
<_VariantDataset shapes: (), types: tf.int64>


In [5]:
for window in dataset:
    for tensor in window:
        print(tensor, end=" ")
    print()

tf.Tensor(0, shape=(), dtype=int64) tf.Tensor(1, shape=(), dtype=int64) tf.Tensor(2, shape=(), dtype=int64) tf.Tensor(3, shape=(), dtype=int64) tf.Tensor(4, shape=(), dtype=int64) 
tf.Tensor(1, shape=(), dtype=int64) tf.Tensor(2, shape=(), dtype=int64) tf.Tensor(3, shape=(), dtype=int64) tf.Tensor(4, shape=(), dtype=int64) tf.Tensor(5, shape=(), dtype=int64) 
tf.Tensor(2, shape=(), dtype=int64) tf.Tensor(3, shape=(), dtype=int64) tf.Tensor(4, shape=(), dtype=int64) tf.Tensor(5, shape=(), dtype=int64) tf.Tensor(6, shape=(), dtype=int64) 
tf.Tensor(3, shape=(), dtype=int64) tf.Tensor(4, shape=(), dtype=int64) tf.Tensor(5, shape=(), dtype=int64) tf.Tensor(6, shape=(), dtype=int64) tf.Tensor(7, shape=(), dtype=int64) 
tf.Tensor(4, shape=(), dtype=int64) tf.Tensor(5, shape=(), dtype=int64) tf.Tensor(6, shape=(), dtype=int64) tf.Tensor(7, shape=(), dtype=int64) tf.Tensor(8, shape=(), dtype=int64) 
tf.Tensor(5, shape=(), dtype=int64) tf.Tensor(6, shape=(), dtype=int64) tf.Tensor(7, shape=(), 

In [6]:
for window in dataset:
    for tensor in window:
        print(tensor.numpy(), end=" ")
    print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 
6 7 8 9 
7 8 9 
8 9 
9 


In [7]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
for window in dataset:
    for tensor in window:
        print(tensor.numpy(), end=" ")
    print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 


In [ ]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset

In [ ]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
for window in dataset:
    print(window)

#### (?1) Why we have to use <code>flat_map()</code>?
What would happen had we used <code>map()</code> instead?

In [ ]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.map(lambda window: window.batch(5))
dataset

In [ ]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.map(lambda window: window.batch(5))
for window in dataset:
    print(window)

In [ ]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.map(lambda window: window.batch(5))
for window in dataset:
    for tensor in window:
        print(tensor.numpy(), end=" ")
    print()

In [ ]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
for window in dataset:
    print(window.numpy())

In [ ]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1]))
dataset

In [ ]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1]))
for instance in dataset:
    print(instance)

In [ ]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1]))
for x, y in dataset:
    print(x.numpy(), y.numpy())

In [ ]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
for x, y in dataset:
    print(x.numpy(), y.numpy())

In [ ]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size=10)
for x, y in dataset:
    print(x.numpy(), y.numpy())

#### (?1) What's <code><b>buffer_size=10</b></code>?

In [ ]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size=10)
dataset = dataset.batch(2).prefetch(1)
for x, y in dataset:
    print(f"x =\n{x}")
    print(f"y =\n{y}")
    print()

#### (?2) What's <code><b>prefetch(1)</b></code>?

In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt


def trend(time, slope=0):
    return slope * time

def seasonal_pattern(season_time):
    """Just an arbitrary pattern, you can change it if you wish"""
    return np.where(season_time < 0.4,
                    np.cos(season_time * 2 * np.pi),
                    1 / np.exp(3 * season_time))

def seasonality(time, period, amplitude=1, phase=0):
    """Repeats the same pattern at each period"""
    season_time = ((time + phase) % period) / period
    return amplitude * seasonal_pattern(season_time)

def noise(time, noise_level=1, seed=None):
    rnd = np.random.RandomState(seed)
    return rnd.randn(len(time)) * noise_level

time = np.arange(4 * 365 + 1, dtype="float32")
baseline = 10
series = trend(time, 0.1)  
baseline = 10
amplitude = 40
slope = 0.05
noise_level = 5

# Create the series
series = baseline + trend(time, slope) + seasonality(time, period=365, amplitude=amplitude)
# Update with noise
series += noise(time, noise_level, seed=42)

window_size = 20
batch_size = 32
shuffle_buffer_size = 1000

In [2]:
series.shape

(1461,)

In [3]:
dataset = tf.data.Dataset.from_tensor_slices(series)
for i in dataset.take(2):
    print(i)

tf.Tensor(52.48357, shape=(), dtype=float32)
tf.Tensor(49.35275, shape=(), dtype=float32)


In [4]:
dataset = tf.data.Dataset.from_tensor_slices(series)
dataset = dataset.window(window_size + 1, shift=1, drop_remainder=True)
for i in dataset.take(2):
    print(i)

<_VariantDataset shapes: (), types: tf.float32>
<_VariantDataset shapes: (), types: tf.float32>


In [5]:
dataset = tf.data.Dataset.from_tensor_slices(series)
dataset = dataset.window(window_size + 1, shift=1, drop_remainder=True)
for n, i in enumerate(dataset.take(2)):
    print(n)
    for j in i:
        print(j)

0
tf.Tensor(52.48357, shape=(), dtype=float32)
tf.Tensor(49.35275, shape=(), dtype=float32)
tf.Tensor(53.314735, shape=(), dtype=float32)
tf.Tensor(57.711823, shape=(), dtype=float32)
tf.Tensor(48.934444, shape=(), dtype=float32)
tf.Tensor(48.931244, shape=(), dtype=float32)
tf.Tensor(57.982895, shape=(), dtype=float32)
tf.Tensor(53.897125, shape=(), dtype=float32)
tf.Tensor(47.67393, shape=(), dtype=float32)
tf.Tensor(52.68371, shape=(), dtype=float32)
tf.Tensor(47.591717, shape=(), dtype=float32)
tf.Tensor(47.506374, shape=(), dtype=float32)
tf.Tensor(50.959415, shape=(), dtype=float32)
tf.Tensor(40.086178, shape=(), dtype=float32)
tf.Tensor(40.919415, shape=(), dtype=float32)
tf.Tensor(46.612473, shape=(), dtype=float32)
tf.Tensor(44.228207, shape=(), dtype=float32)
tf.Tensor(50.720642, shape=(), dtype=float32)
tf.Tensor(44.454983, shape=(), dtype=float32)
tf.Tensor(41.76799, shape=(), dtype=float32)
tf.Tensor(55.980938, shape=(), dtype=float32)
1
tf.Tensor(49.35275, shape=(), dtype

In [6]:
dataset = tf.data.Dataset.from_tensor_slices(series)
dataset = dataset.batch(window_size + 1, drop_remainder=True)
for i in dataset.take(2):
    print(i)

tf.Tensor(
[52.48357  49.35275  53.314735 57.711823 48.934444 48.931244 57.982895
 53.897125 47.67393  52.68371  47.591717 47.506374 50.959415 40.086178
 40.919415 46.612473 44.228207 50.720642 44.454983 41.76799  55.980938], shape=(21,), dtype=float32)
tf.Tensor(
[47.335835 48.6033   40.93184  45.11266  48.15732  41.6051   48.985233
 43.839634 45.109936 43.275043 55.249832 45.615612 40.079105 49.154957
 38.602703 45.406162 34.208767 37.00193  44.25351  46.578594 43.35101 ], shape=(21,), dtype=float32)


In [7]:
dataset = tf.data.Dataset.from_tensor_slices(series)
dataset = dataset.batch(window_size + 1, drop_remainder=True)
for i in dataset.take(2):
    print(type(i))

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [8]:
dataset = tf.data.Dataset.from_tensor_slices(series)
for i in dataset.take(2):
    print(type(i))

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


The diff btw <code><b>batch()</b></code> and <code><b>window()</b></code> is that
- <code><b>window()</b></code> creates sub-datasets
- <code><b>batch()</b></code> only groups instances of the original dataset together.

In [17]:
help(dataset.flat_map)

Help on method flat_map in module tensorflow.python.data.ops.dataset_ops:

flat_map(map_func) method of tensorflow.python.data.ops.dataset_ops.BatchDataset instance
    Maps `map_func` across this dataset and flattens the result.
    
    Use `flat_map` if you want to make sure that the order of your dataset
    stays the same. For example, to flatten a dataset of batches into a
    dataset of their elements:
    
    >>> dataset = Dataset.from_tensor_slices([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    >>> dataset = dataset.flat_map(lambda x: Dataset.from_tensor_slices(x))
    >>> list(dataset.as_numpy_iterator())
    [1, 2, 3, 4, 5, 6, 7, 8, 9]
    
    `tf.data.Dataset.interleave()` is a generalization of `flat_map`, since
    `flat_map` produces the same output as
    `tf.data.Dataset.interleave(cycle_length=1)`
    
    Args:
      map_func: A function mapping a dataset element to a dataset.
    
    Returns:
      Dataset: A `Dataset`.



In [11]:
dataset = tf.data.Dataset.from_tensor_slices([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
for i in dataset.take(2):
    print(i)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [12]:
dataset = tf.data.Dataset.from_tensor_slices([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
for i in dataset.take(2):
    print(type(i))

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [13]:
dataset = tf.data.Dataset.from_tensor_slices([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
dataset = dataset.flat_map(lambda x: tf.data.Dataset.from_tensor_slices(x))
list(dataset.as_numpy_iterator())

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
dataset = tf.data.Dataset.from_tensor_slices(series)
dataset = dataset.window(window_size + 1, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(window_size + 1))
for i in dataset.take(2):
    print(i)

tf.Tensor(
[52.48357  49.35275  53.314735 57.711823 48.934444 48.931244 57.982895
 53.897125 47.67393  52.68371  47.591717 47.506374 50.959415 40.086178
 40.919415 46.612473 44.228207 50.720642 44.454983 41.76799  55.980938], shape=(21,), dtype=float32)
tf.Tensor(
[49.35275  53.314735 57.711823 48.934444 48.931244 57.982895 53.897125
 47.67393  52.68371  47.591717 47.506374 50.959415 40.086178 40.919415
 46.612473 44.228207 50.720642 44.454983 41.76799  55.980938 47.335835], shape=(21,), dtype=float32)


In [25]:
dataset = tf.data.Dataset.from_tensor_slices(series)
dataset = dataset.window(window_size + 1, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window)
for i in dataset.take(window_size + 3):
    print(i)

tf.Tensor(52.48357, shape=(), dtype=float32)
tf.Tensor(49.35275, shape=(), dtype=float32)
tf.Tensor(53.314735, shape=(), dtype=float32)
tf.Tensor(57.711823, shape=(), dtype=float32)
tf.Tensor(48.934444, shape=(), dtype=float32)
tf.Tensor(48.931244, shape=(), dtype=float32)
tf.Tensor(57.982895, shape=(), dtype=float32)
tf.Tensor(53.897125, shape=(), dtype=float32)
tf.Tensor(47.67393, shape=(), dtype=float32)
tf.Tensor(52.68371, shape=(), dtype=float32)
tf.Tensor(47.591717, shape=(), dtype=float32)
tf.Tensor(47.506374, shape=(), dtype=float32)
tf.Tensor(50.959415, shape=(), dtype=float32)
tf.Tensor(40.086178, shape=(), dtype=float32)
tf.Tensor(40.919415, shape=(), dtype=float32)
tf.Tensor(46.612473, shape=(), dtype=float32)
tf.Tensor(44.228207, shape=(), dtype=float32)
tf.Tensor(50.720642, shape=(), dtype=float32)
tf.Tensor(44.454983, shape=(), dtype=float32)
tf.Tensor(41.76799, shape=(), dtype=float32)
tf.Tensor(55.980938, shape=(), dtype=float32)
tf.Tensor(49.35275, shape=(), dtype=flo

In [26]:
dataset = tf.data.Dataset.from_tensor_slices(series)
dataset = dataset.window(window_size + 1, shift=1, drop_remainder=True)
for i in dataset.take(2):
    print(type(i))

<class 'tensorflow.python.data.ops.dataset_ops._VariantDataset'>
<class 'tensorflow.python.data.ops.dataset_ops._VariantDataset'>


What about <code><b>map()</b></code>? Does its returned value restricted to be a <code><b>dataset</b></code> as well?


In [27]:
dataset = tf.data.Dataset.from_tensor_slices(series)
dataset = dataset.window(window_size + 1, shift=1, drop_remainder=True)
dataset = dataset.map(lambda window: window.batch(window_size + 1))
for i in dataset.take(2):
    print(i)

<_VariantDataset shapes: (None,), types: tf.float32>
<_VariantDataset shapes: (None,), types: tf.float32>


In [28]:
dataset = tf.data.Dataset.from_tensor_slices(series)
dataset = dataset.window(window_size + 1, shift=1, drop_remainder=True)
dataset = dataset.map(lambda window: window.batch(window_size + 1))
for n, i in enumerate(dataset.take(2)):
    print(n)
    for j in i:
        print(j)

0
tf.Tensor(
[52.48357  49.35275  53.314735 57.711823 48.934444 48.931244 57.982895
 53.897125 47.67393  52.68371  47.591717 47.506374 50.959415 40.086178
 40.919415 46.612473 44.228207 50.720642 44.454983 41.76799  55.980938], shape=(21,), dtype=float32)
1
tf.Tensor(
[49.35275  53.314735 57.711823 48.934444 48.931244 57.982895 53.897125
 47.67393  52.68371  47.591717 47.506374 50.959415 40.086178 40.919415
 46.612473 44.228207 50.720642 44.454983 41.76799  55.980938 47.335835], shape=(21,), dtype=float32)


<code><b>flat_map()</b></code> dụng để <code><b>flat</b></code> 掉 <code><b>dataset</b></code>.

For example, the result of
<pre>
dataset = tf.data.Dataset.from_tensor_slices(series)
dataset = dataset.window(window_size + 1, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(window_size + 1))
</pre>
is nothing but a <code><b>dataset</b></code> of <code>tf.Tensor</code>s, each of <code><b>shape=(21,)</b></code>.


### <code>shuffle()</code> and <code>map()</code>

In [30]:
shuffle_buffer_size

1000

In [31]:
dataset = tf.data.Dataset.from_tensor_slices(series)
dataset = dataset.window(window_size + 1, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(window_size + 1))
dataset = dataset.shuffle(shuffle_buffer_size)
list(dataset.as_numpy_iterator())

[array([21.541426, 35.955315, 20.655773, 25.61978 , 28.487524, 35.054302,
        20.683037, 33.692867, 27.943205, 22.999773, 30.233395, 28.934015,
        24.953756, 28.320253, 26.06135 , 28.57245 , 31.332735, 35.969654,
        21.868246, 38.740505, 18.333178], dtype=float32),
 array([46.612473, 44.228207, 50.720642, 44.454983, 41.76799 , 55.980938,
        47.335835, 48.6033  , 40.93184 , 45.11266 , 48.15732 , 41.6051  ,
        48.985233, 43.839634, 45.109936, 43.275043, 55.249832, 45.615612,
        40.079105, 49.154957, 38.602703], dtype=float32),
 array([65.356606, 61.307972, 57.718082, 68.47362 , 67.35454 , 63.60032 ,
        73.322525, 58.73252 , 56.449394, 60.612007, 63.838596, 65.278656,
        62.85165 , 65.81443 , 57.79322 , 71.26694 , 63.634983, 69.63028 ,
        65.755905, 66.32495 , 66.88934 ], dtype=float32),
 array([ 0.36368567,  4.538722  , -0.2369535 ,  4.9011045 , 47.34658   ,
        46.35441   , 42.963524  , 44.570477  , 51.18507   , 49.86728   ,
        42.430

In [33]:
dataset = tf.data.Dataset.from_tensor_slices(series)
dataset = dataset.window(window_size + 1, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(window_size + 1))
dataset = dataset.shuffle(shuffle_buffer_size).map(lambda tensor: (tensor[:-1], tensor[-1]))
list(dataset.as_numpy_iterator())

[(array([65.38417 , 62.19856 , 65.38135 , 69.759796, 59.24037 , 65.01967 ,
         60.836647, 70.29547 , 56.687828, 61.493233, 66.15852 , 72.08523 ,
         63.914536, 61.453503, 73.62201 , 56.963406, 53.19721 , 66.379585,
         61.65801 , 59.0514  ], dtype=float32),
  67.68912),
 (array([29.55496 , 25.05581 , 27.14825 , 25.743662, 25.281895, 32.497025,
         30.054634, 24.825788, 32.809357, 29.869114, 32.418423, 31.52398 ,
         24.252817, 25.619074, 32.178864, 31.51689 , 28.383394, 29.097626,
         34.92262 , 25.599964], dtype=float32),
  31.317053),
 (array([16.742033  , -0.23790547,  9.138161  ,  2.6470213 ,  3.0502167 ,
          2.1182992 ,  0.36368567,  4.538722  , -0.2369535 ,  4.9011045 ,
         47.34658   , 46.35441   , 42.963524  , 44.570477  , 51.18507   ,
         49.86728   , 42.430267  , 47.770836  , 50.988007  , 38.8417    ],
        dtype=float32),
  49.86395),
 (array([31.43617 , 31.405706, 30.38625 , 30.17146 , 29.214622, 37.80533 ,
         38.427612

We could have chosen not to shuffle to make things more clear 

In [34]:
dataset = tf.data.Dataset.from_tensor_slices(series)
dataset = dataset.window(window_size + 1, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(window_size + 1))
dataset = dataset.map(lambda tensor: (tensor[:-1], tensor[-1]))
list(dataset.as_numpy_iterator())

[(array([52.48357 , 49.35275 , 53.314735, 57.711823, 48.934444, 48.931244,
         57.982895, 53.897125, 47.67393 , 52.68371 , 47.591717, 47.506374,
         50.959415, 40.086178, 40.919415, 46.612473, 44.228207, 50.720642,
         44.454983, 41.76799 ], dtype=float32),
  55.980938),
 (array([49.35275 , 53.314735, 57.711823, 48.934444, 48.931244, 57.982895,
         53.897125, 47.67393 , 52.68371 , 47.591717, 47.506374, 50.959415,
         40.086178, 40.919415, 46.612473, 44.228207, 50.720642, 44.454983,
         41.76799 , 55.980938], dtype=float32),
  47.335835),
 (array([53.314735, 57.711823, 48.934444, 48.931244, 57.982895, 53.897125,
         47.67393 , 52.68371 , 47.591717, 47.506374, 50.959415, 40.086178,
         40.919415, 46.612473, 44.228207, 50.720642, 44.454983, 41.76799 ,
         55.980938, 47.335835], dtype=float32),
  48.6033),
 (array([57.711823, 48.934444, 48.931244, 57.982895, 53.897125, 47.67393 ,
         52.68371 , 47.591717, 47.506374, 50.959415, 40.086178, 40

In [35]:
dataset = tf.data.Dataset.from_tensor_slices(series)
dataset = dataset.window(window_size + 1, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(window_size + 1))
dataset = dataset.map(lambda tensor: (tensor[:-1], tensor[-1]))
for i in dataset.take(2):
    print(type(i))

<class 'tuple'>
<class 'tuple'>


In [36]:
dataset = tf.data.Dataset.from_tensor_slices(series)
dataset = dataset.window(window_size + 1, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(window_size + 1))
dataset = dataset.map(lambda tensor: (tensor[:-1], tensor[-1]))
for i in dataset.take(2):
    print(i)

(<tf.Tensor: shape=(20,), dtype=float32, numpy=
array([52.48357 , 49.35275 , 53.314735, 57.711823, 48.934444, 48.931244,
       57.982895, 53.897125, 47.67393 , 52.68371 , 47.591717, 47.506374,
       50.959415, 40.086178, 40.919415, 46.612473, 44.228207, 50.720642,
       44.454983, 41.76799 ], dtype=float32)>, <tf.Tensor: shape=(), dtype=float32, numpy=55.980938>)
(<tf.Tensor: shape=(20,), dtype=float32, numpy=
array([49.35275 , 53.314735, 57.711823, 48.934444, 48.931244, 57.982895,
       53.897125, 47.67393 , 52.68371 , 47.591717, 47.506374, 50.959415,
       40.086178, 40.919415, 46.612473, 44.228207, 50.720642, 44.454983,
       41.76799 , 55.980938], dtype=float32)>, <tf.Tensor: shape=(), dtype=float32, numpy=47.335835>)


### <code>batch()</code>

In [38]:
batch_size = 3

In [39]:
dataset = tf.data.Dataset.from_tensor_slices(series)
dataset = dataset.window(window_size + 1, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(window_size + 1))
dataset = dataset.map(lambda tensor: (tensor[:-1], tensor[-1]))
dataset = dataset.batch(batch_size)
list(dataset.as_numpy_iterator())

[(array([[52.48357 , 49.35275 , 53.314735, 57.711823, 48.934444, 48.931244,
          57.982895, 53.897125, 47.67393 , 52.68371 , 47.591717, 47.506374,
          50.959415, 40.086178, 40.919415, 46.612473, 44.228207, 50.720642,
          44.454983, 41.76799 ],
         [49.35275 , 53.314735, 57.711823, 48.934444, 48.931244, 57.982895,
          53.897125, 47.67393 , 52.68371 , 47.591717, 47.506374, 50.959415,
          40.086178, 40.919415, 46.612473, 44.228207, 50.720642, 44.454983,
          41.76799 , 55.980938],
         [53.314735, 57.711823, 48.934444, 48.931244, 57.982895, 53.897125,
          47.67393 , 52.68371 , 47.591717, 47.506374, 50.959415, 40.086178,
          40.919415, 46.612473, 44.228207, 50.720642, 44.454983, 41.76799 ,
          55.980938, 47.335835]], dtype=float32),
  array([55.980938, 47.335835, 48.6033  ], dtype=float32)),
 (array([[57.711823, 48.934444, 48.931244, 57.982895, 53.897125, 47.67393 ,
          52.68371 , 47.591717, 47.506374, 50.959415, 40.086178,

In [40]:
dataset = tf.data.Dataset.from_tensor_slices(series)
dataset = dataset.window(window_size + 1, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(window_size + 1))
dataset = dataset.map(lambda tensor: (tensor[:-1], tensor[-1]))
dataset = dataset.batch(batch_size).prefetch(1)
list(dataset.as_numpy_iterator())

[(array([[52.48357 , 49.35275 , 53.314735, 57.711823, 48.934444, 48.931244,
          57.982895, 53.897125, 47.67393 , 52.68371 , 47.591717, 47.506374,
          50.959415, 40.086178, 40.919415, 46.612473, 44.228207, 50.720642,
          44.454983, 41.76799 ],
         [49.35275 , 53.314735, 57.711823, 48.934444, 48.931244, 57.982895,
          53.897125, 47.67393 , 52.68371 , 47.591717, 47.506374, 50.959415,
          40.086178, 40.919415, 46.612473, 44.228207, 50.720642, 44.454983,
          41.76799 , 55.980938],
         [53.314735, 57.711823, 48.934444, 48.931244, 57.982895, 53.897125,
          47.67393 , 52.68371 , 47.591717, 47.506374, 50.959415, 40.086178,
          40.919415, 46.612473, 44.228207, 50.720642, 44.454983, 41.76799 ,
          55.980938, 47.335835]], dtype=float32),
  array([55.980938, 47.335835, 48.6033  ], dtype=float32)),
 (array([[57.711823, 48.934444, 48.931244, 57.982895, 53.897125, 47.67393 ,
          52.68371 , 47.591717, 47.506374, 50.959415, 40.086178,

In [41]:
dataset = tf.data.Dataset.from_tensor_slices(series)
dataset = dataset.window(window_size + 1, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(window_size + 1))
dataset = dataset.map(lambda tensor: (tensor[:-1], tensor[-1]))
dataset = dataset.batch(batch_size)
for i in dataset.take(2):
    print(type(i))

<class 'tuple'>
<class 'tuple'>


In [44]:
dataset = tf.data.Dataset.from_tensor_slices(series)
dataset = dataset.window(window_size + 1, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(window_size + 1))
dataset = dataset.map(lambda tensor: (tensor[:-1], tensor[-1]))
dataset = dataset.batch(batch_size)
for i in dataset.take(2):
    print(len(i))

2
2


In [48]:
dataset = tf.data.Dataset.from_tensor_slices(series)
dataset = dataset.window(window_size + 1, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(window_size + 1))
dataset = dataset.map(lambda tensor: (tensor[:-1], tensor[-1]))
dataset = dataset.batch(batch_size)
for n, i in enumerate(dataset.take(2)):
    print(n)
    print(i)
    for a, b in i:
        print(f"a.numpy().shape = {a.numpy().shape}, b.numpy().shape = {b.numpy().shape}")

0
(<tf.Tensor: shape=(3, 20), dtype=float32, numpy=
array([[52.48357 , 49.35275 , 53.314735, 57.711823, 48.934444, 48.931244,
        57.982895, 53.897125, 47.67393 , 52.68371 , 47.591717, 47.506374,
        50.959415, 40.086178, 40.919415, 46.612473, 44.228207, 50.720642,
        44.454983, 41.76799 ],
       [49.35275 , 53.314735, 57.711823, 48.934444, 48.931244, 57.982895,
        53.897125, 47.67393 , 52.68371 , 47.591717, 47.506374, 50.959415,
        40.086178, 40.919415, 46.612473, 44.228207, 50.720642, 44.454983,
        41.76799 , 55.980938],
       [53.314735, 57.711823, 48.934444, 48.931244, 57.982895, 53.897125,
        47.67393 , 52.68371 , 47.591717, 47.506374, 50.959415, 40.086178,
        40.919415, 46.612473, 44.228207, 50.720642, 44.454983, 41.76799 ,
        55.980938, 47.335835]], dtype=float32)>, <tf.Tensor: shape=(3,), dtype=float32, numpy=array([55.980938, 47.335835, 48.6033  ], dtype=float32)>)


ValueError: too many values to unpack (expected 2)

In [42]:
dataset = tf.data.Dataset.from_tensor_slices(series)
dataset = dataset.window(window_size + 1, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(window_size + 1))
dataset = dataset.map(lambda tensor: (tensor[:-1], tensor[-1]))
dataset = dataset.batch(batch_size)
for n, i in enumerate(dataset.take(2)):
    print(n)
    for a, b in i:
        print(f"a.shape = {a.shape}, b.shape = {b.shape}")

0


ValueError: too many values to unpack (expected 2)

In [ ]:
dataset = tf.data.Dataset.range(10)
for val in dataset:
   print(val.numpy())

In [ ]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1)
for window_dataset in dataset:
  for val in window_dataset:
    print(val.numpy(), end=" ")
  print()

In [ ]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
for window_dataset in dataset:
  for val in window_dataset:
    print(val.numpy(), end=" ")
  print()

In [ ]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
for window in dataset:
  print(window.numpy())


In [ ]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
for x,y in dataset:
  print(x.numpy(), y.numpy())

In [ ]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size=10)
for x,y in dataset:
  print(x.numpy(), y.numpy())


In [ ]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size=10)
dataset = dataset.batch(2).prefetch(1)
for x,y in dataset:
  print("x = ", x.numpy())
  print("y = ", y.numpy())
